// Root myDeserializedClass = JsonConvert.DeserializeObject<Root>(myJsonResponse);
// Accidentally discovered this website: https://json2csharp.com that made this a whole lot easier
#nullable disable
public class Video
{
    public string title { get; set; }
    public string description { get; set; }
    public DateTime uploadDate { get; set; }
    public string uploader { get; set; }
    public string uploaderUrl { get; set; }
    public string uploaderAvatar { get; set; }
    public string thumbnailUrl { get; set; }
    public object hls { get; set; }
    public object dash { get; set; }
    public object lbryId { get; set; }
    public string category { get; set; }
    public string license { get; set; }
    public string visibility { get; set; }
    public List<object> tags { get; set; }
    public List<object> metaInfo { get; set; }
    public bool uploaderVerified { get; set; }
    public int duration { get; set; }
    public int views { get; set; }
    public int likes { get; set; }
    public int dislikes { get; set; }
    public int uploaderSubscriberCount { get; set; }
    public long uploaded { get; set; }
    public List<AudioStream> audioStreams { get; set; }
    public List<VideoStream> videoStreams { get; set; }
    public List<RelatedStream> relatedStreams { get; set; }
    public List<Subtitle> subtitles { get; set; }
    public bool livestream { get; set; }
    public string proxyUrl { get; set; }
    public List<object> chapters { get; set; }
    public List<PreviewFrame> previewFrames { get; set; }
}

public class AudioStream
{
    public string url { get; set; }
    public string format { get; set; }
    public string quality { get; set; }
    public string mimeType { get; set; }
    public string codec { get; set; }
    public object audioTrackId { get; set; }
    public object audioTrackName { get; set; }
    public object audioTrackType { get; set; }
    public object audioTrackLocale { get; set; }
    public bool videoOnly { get; set; }
    public int itag { get; set; }
    public int bitrate { get; set; }
    public int initStart { get; set; }
    public int initEnd { get; set; }
    public int indexStart { get; set; }
    public int indexEnd { get; set; }
    public int width { get; set; }
    public int height { get; set; }
    public int fps { get; set; }
    public long contentLength { get; set; }
}

public class PreviewFrame
{
    public List<string> urls { get; set; }
    public int frameWidth { get; set; }
    public int frameHeight { get; set; }
    public int totalCount { get; set; }
    public int durationPerFrame { get; set; }
    public int framesPerPageX { get; set; }
    public int framesPerPageY { get; set; }
}

public class RelatedStream
{
    public string url { get; set; }
    public string type { get; set; }
    public string title { get; set; }
    public string thumbnail { get; set; }
    public string uploaderName { get; set; }
    public string uploaderUrl { get; set; }
    public string uploaderAvatar { get; set; }
    public string uploadedDate { get; set; }
    public object shortDescription { get; set; }
    public int duration { get; set; }
    public int views { get; set; }
    public object uploaded { get; set; }
    public bool uploaderVerified { get; set; }
    public bool isShort { get; set; }
}


public class Subtitle
{
    public string url { get; set; }
    public string mimeType { get; set; }
    public string name { get; set; }
    public string code { get; set; }
    public bool autoGenerated { get; set; }
}

public class VideoStream
{
    public string url { get; set; }
    public string format { get; set; }
    public string quality { get; set; }
    public string mimeType { get; set; }
    public string codec { get; set; }
    public object audioTrackId { get; set; }
    public object audioTrackName { get; set; }
    public object audioTrackType { get; set; }
    public object audioTrackLocale { get; set; }
    public bool videoOnly { get; set; }
    public int itag { get; set; }
    public int bitrate { get; set; }
    public int initStart { get; set; }
    public int initEnd { get; set; }
    public int indexStart { get; set; }
    public int indexEnd { get; set; }
    public int width { get; set; }
    public int height { get; set; }
    public int fps { get; set; }
    public long contentLength { get; set; }
}


